### ISSUE TITLE
[Feat] PlaceViewCollectionViewCell 레이아웃 세팅

### ISSUE THREAD

**Issue by jaminleee** [SOPT-33RD-APP-NAVERPAY/NaverPay-iOS#22]
## 🛠 Issue

- NearPlaceCollectionViewCell 레이아웃 세팅
- RecommendCollectionViewCell 레이아웃 세팅
- BrandCollectionViewCell 레이아웃 세팅

## 📝 To-do

- [ ] Place/NearPlaceCollectionViewCell 레이아웃 세팅
- [ ] RecommendCollectionViewCell 레이아웃 세팅
- [ ] BrandCollectionViewCell 레이아웃 세팅
