### ISSUE TITLE
[Feat] HomeView Section2,3,4 UI 구현

### ISSUE THREAD

**Issue by kim-seonwoo** [SOPT-33RD-APP-NAVERPAY/NaverPay-iOS#25]
## 🛠 Issue

- HomeView Section2,3,4 UI를 구현합니다.

## 📝 To-do

- [x] Section2 UI 구현
- [x] Section3 UI 구현
- [x] Section4 UI 구현
