### ISSUE TITLE
[Feat] 더미 데이터 추가하여 연결

### ISSUE THREAD

**Issue by kim-seonwoo** [SOPT-33RD-APP-NAVERPAY/NaverPay-iOS#29]
## 🛠 Issue

- API 명세에 따라 더미 데이터 파일을 추가하고 연결합니다. 
-  고정된 데이터 또한 데이터 모델을 작성하여 cell과 연동 시킵니다.
-  카드 선택 탭 기능을 구현합니다.
## 📝 To-do

- [x] 더미 데이터 모델 파일 만들기
- [x] 더미 데이터에 따른 값 연결하기
- [x] 카드 데이터 모델 작성
- [x] 이벤트 데이터 모델 작성
- [x] 카드 선택 함수 구현
